# This is a basic workflow to help you get started with Actions
# Depende de los secretos que se listan en el código.

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-produccion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Control the run per-branch
    if: contains(github.ref, 'master')
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - id: deploy
        name: Dokku Deploy action
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          # The ssh private key to the dokku instance. WARNING: use a secret! Do not pass a plain text value!
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          # The user to use for ssh (Default: dokku)
          dokku-user: ${{ secrets.DOKKU_USER_PRODUCTION }} # optional, default is dokku
          # The dokku host to ssh into
          dokku-host: ${{ secrets.DOKKU_HOST_PRODUCTION }}
          # The dokku app name
          app-name: ${{ secrets.APP_NAME_PRODUCTION }}
          # The branch to push on the remote repository (Default: master)
          remote-branch: master # optional, default is master
          # Additional flags to be passed to the git push command. Could be used to force push
          git-push-flags: --force # optional, default is
